### ISSUE TITLE
Advice on S3 Setup

### ISSUE THREAD

**Issue by rwatts3** [orionjs/s3#1]
Attempted to set up S3 today and upon completing the instructions.  When ever I upload a new image and try to view it.  I get an error saying that I do not have permission to view the file.  I went through the instructions at least 3 time .

Any advice ?

**Comment by nicolaslopezj** [comment]
Did you:

- Put the right credentials in the admin?
- Configure correctly CORS configuration of your bucket?
- Edit correctly the bucket policy?

**Comment by rwatts3** [comment]
Yes I did each of those with no success.

**Comment by nicolaslopezj** [comment]
And did you replace the bucket name of the bucket policy?

**Comment by rwatts3** [comment]
Sure did. I'll give it a nother try but it just says that I do not have permission to view the file. and the file appears broken in the orion.

**Comment by nicolaslopezj** [comment]
I have seen that error when the file is not uploaded. When you navigate to your bucket in aws console, do you see the file?

**Comment by rwatts3** [comment]
No I didn't the file never made to aws

**Comment by nicolaslopezj** [comment]
Try now

**Comment by rwatts3** [comment]
Ok I will give it a try and let you know, 

Thanks.

**Comment by marccantwell** [comment]
Same issues on my end.  Fully configured on AWS not able to upload any files. 
```
=> App running at: http://localhost:3000/
I20150324-13:07:13.253(-7)? Exception in callback of async function: Error: NetworkingError: Hostname/IP doesn't match certificate's altnames [aws.createMpu]
I20150324-13:07:13.253(-7)?     at packages/lepozepo:s3/server/methods.coffee:162:17
I20150324-13:07:13.253(-7)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
=> Exited with code: 0
```

Network request log:
http://cl.ly/image/1Q1J0l37170U
http://cl.ly/image/2l2l1B2B2p2g

Found this (http://blog.vanamco.com/proxy-requests-in-node-js/):
To do the encryption and decryption, we use node.js’s TLS module. The tls.connect method accepts an options argument which contains the socket we received from the connect event handler. Make sure to also include the host in the options, even though the node.js docs say the host will be ignored when you’re passing a socket. If you don’t pass the host, an error will be thrown, “Hostname/IP doesn’t match certificate’s altnames”. As a second argument, tls.connect accepts a callback function (a listener to the secureConnect event, really), in which we do our HTTP request (manually, in this snippet) writing to the tls.ClearTextStream object returned by tls.connect.

**Comment by nicolaslopezj** [comment]
@marccantwell are you using the latest version?

**Comment by marccantwell** [comment]
I believe so

**Comment by nicolaslopezj** [comment]
Please confirm with the versions on atmosphere

**Comment by marccantwell** [comment]
orionjs:s3@0.0.12

**Comment by nicolaslopezj** [comment]
Are you using https? Did this work on local host?

**Comment by marccantwell** [comment]
not yet, just using http via localhost for now.  haven't deployed.

**Comment by nicolaslopezj** [comment]
Ok, I will have to take a closer look at this.

**Comment by marccantwell** [comment]
Its working now.  Updated to meteor 1.0.5 seems to have helped.  Not sure why it is working now and it wasn't before.

**Comment by nicolaslopezj** [comment]
Great

**Comment by marccantwell** [comment]
Thanks for your help.  This is a great platform, I'm enjoying working with it.  Lot's of potential.

**Comment by rwatts3** [comment]
+1 @marccantwell  I agree 100%

**Comment by rwatts3** [comment]
Something to note. I noticed that if you are working on a localhost:3000 and you activate the policy, when you push the code to dev or to your production server you will have to repeat the process unless you push up your local mongo collection with it. This is not a bug , it is simply the fact that the s3 credentials are not carried over. 

Anyone having this issue could follow these steps and everything will work as expected.
