### ISSUE TITLE
Example s3 config file

### ISSUE THREAD

**Issue by marccantwell** [orionjs/s3#2]
Can you provide an example s3 config file?

**Comment by nicolaslopezj** [comment]
Its not a file, its a url

**Comment by marccantwell** [comment]
Sorry, I'm just not sure where I config in the meteor app to point to my bucket.

**Comment by nicolaslopezj** [comment]
You must go to the admin, then click on config, then aws

**Comment by marccantwell** [comment]
There it is, couldn't find it.  Thank you.  Here is an image for your Readme:
http://cl.ly/image/3H2g1u1C0G0K
